name: Docker Image CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull Microsoft SQL Server Docker image
      run: docker pull mcr.microsoft.com/mssql/server:2022-latest

    - name: Build the Docker image
      run: docker build . --file ./docker/mvc/up.ps1 --tag my-image-name:$(date +%s)
